# Generated by Django 4.1.1 on 2022-09-24 15:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestPupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=40)),
                ('familya', models.CharField(max_length=40)),
                ('otasining_ismi', models.CharField(max_length=40)),
                ('tugilgan_yil', models.DateField()),
                ('sinf', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=40)),
                ('familya', models.CharField(max_length=40)),
                ('otasining_ismi', models.CharField(max_length=40)),
                ('toifa', models.CharField(choices=[['Oliy toifa', 'Oliy toifa'], ['1-toifa', '1-toifa'], ['2-toifa', '2-toifa']], max_length=50)),
                ('fan', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=41, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blog')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
    ]
